### ISSUE TITLE
ReferenceError: onClick is not defined in ssr mode

### ISSUE THREAD

**Issue by do4ng** [do4ng/segify#11]
https://segify.vercel.app/repl.html#%3Cscript%3E%0A%20%20function%20onClick()%20%7B%0A%20%20%20%20alert(%22Button%20clicked!%22);%0A%20%20%7D%0A%3C/script%3E%0A%3Cbutton%20$onclick=%22onClick%22%3EClick%20Me!%3C/button%3E%0A

```txt
VM16:161 Uncaught (in promise) ReferenceError: onClick is not defined
    at Component.$$components (eval at Ls (repl-CGJTRqEm.js:188:215), <anonymous>:161:133)
    at eval (eval at Ls (repl-CGJTRqEm.js:188:215), <anonymous>:184:83)
    at Ls (repl-CGJTRqEm.js:188:230)
    at async HTMLButtonElement.h (repl-CGJTRqEm.js:188:1820)
```

**Comment by do4ng** [comment]
Fixed in 0.0.0-beta.16
